version: "3.8"

services:
  hangman:
    image: node:16
    ports:
      - 8080:8080
    volumes:
      - ./:/app
    working_dir: /app
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: bash -c "npm install && npm run serve"
